### ISSUE TITLE
Presenters: Infrastructure leaks into Use Case Layer 

### ISSUE THREAD

**Issue by asterikx** [manakuro/golang-clean-architecture#3]
Hi @manakuro! First, thank you for this excellent showcase.

I have some concerns about the signature of your use case methods: it includes the return type of your presenter's `ResponseUsers` method, so there is information from the infra layer leaking to the use case layer.

https://github.com/manakuro/golang-clean-architecture/blob/1c9b1ca29b08e5ff006922b00aef34f639f6dd81/usecase/interactor/user_interfactor.go#L22-L29

In my case, I'm generating request/response models from an OpenApi file, e.g. I have an `api.User` type. The presenter should take `[]*model.User` and map it to `[]*api.User`,  which requires me to change the signature of the user interactor's `Get` method (which violates Clean Architecture). Moreover, it is not possible to use the interactor implementation with different presenter implementations.

I think for that reason the return type of use case methods is mostly void in Clean Architecture and presenters take care of writing to the output channel. I'm not sure how to this (in an idiomatic way) in Go.

I would appreciate it if you could share your thoughts on this or correct me :)

**Comment by manakuro** [comment]
Hi @asterikx , thank you for your question.

I don't think you always need the Output Port in Clean Architecture because it can't be applied in some cases actually. 

The most important thing is to follow the rule, `the dependencies only point inward in the circle, not point outward and no circulation`. So, if you're not comfortable with the Output Port pattern, just remove it and add the mapping function to the user controller. 

You might write like this.

https://github.com/manakuro/golang-clean-architecture/commit/a5fb2b8420095a03f23871d951305b2b08914eff

The `api.User` struct type is supposed to be defined in `interface/controller` but, I'm not sure how you're trying to implement it so, that depends on you.
