### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by mukeshydv** [manakuro/golang-clean-architecture#4]
How to do transaction in this approach?

Lets assume I've an usecase which is using 2 repositories and I want transaction between methods of these repositories.

**Comment by manakuro** [comment]
Hi @mukeshydv  thank you for your request.

In Clean Architecture, you should implement transactions in the use cases layer so that the whole logic related to the application can be included in it. So, the use cases layer can handle multiple repositories passed by the interface adapters layer.

I've made the PR implemented transaction support so you can check it out.

https://github.com/manakuro/golang-clean-architecture/pull/6
